version: "3.8"

services:
  todo-django:
    build:
      context: .
    container_name: todo-service-dev
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - PORTS=8000
      - DJANGO_CONFIGURATION=production
    command:
      - /bin/sh
      - -c
      - |
        cd /workdir/mytodo
        poetry run python manage.py makemigrations
        poetry run python manage.py migrate
        poetry run python manage.py runserver
    volumes:
      - todo-django:/workdir
    network_mode: host

volumes:
  todo-django:
