# Generated by Django 5.1.7 on 2025-03-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=10)),
                ("bio", models.TextField(blank=True)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "service_user",
                "constraints": [
                    models.UniqueConstraint(fields=("email",), name="unique_email")
                ],
            },
        ),
    ]
